name: Update SVG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # IMPORTANT FIX

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Generate SVG
        run: node generate.js

      - name: Auto Commit SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update SVG
          file_pattern: profile-gitblock.svg
