name: Update SVG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - name: Generate SVG
        run: node generate.js
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add profile-gitblock.svg
          git commit -m "Update SVG" || echo "No changes"
          git push
